$HOME/.config/swaync/theme.css|${scrDir}/wallbashswaync.sh
@define-color bar-bg #1f1f28;   /* Dark Slate */
@define-color main-bg #2a2a37;  /* Soft Charcoal */
@define-color main-fg #dcd7ba;  /* Off-White Cream */
@define-color wb-act-bg #3b3b58; /* Deep Indigo */
@define-color wb-act-fg #ffa066; /* Warm Peach */
@define-color wb-hvr-bg #4c4c67; /* Slate Blue */
@define-color wb-hvr-fg #7e9cd8; /* Soft Sky Blue */
@define-color text #c8c093;     /* Warm Beige */
